msigdb:
  version: 2024.1.Hs
  gmt_files:
  - data/raw/msigdb/c2.cp.reactome.v2024.1.Hs.symbols.gmt
  min_genes_present: 10
  max_genes_present: null
  rna_processing_keywords:
  - SPLICEOSOME
  - RNA_TRANSPORT
  - MRNA_SURVEILLANCE
  - RNA_DEGRADATION
  - MRNA_SPLICING
  - RNA_BINDING
  - RIBONUCLEOPROTEIN
