from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from data.download import collect_download_metadata, download_geo_series, ensure_dir


DEFAULT_ACCESSIONS = ("GSE99039", "GSE6613")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download and cache raw GEO series matrix files for Phase 1 step 1."
    )
    parser.add_argument(
        "--accessions",
        nargs="+",
        default=list(DEFAULT_ACCESSIONS),
        help="GEO series accessions to download and record.",
    )
    parser.add_argument(
        "--raw-dir",
        type=Path,
        default=ROOT / "data" / "raw",
        help="Directory where raw GEO files are cached.",
    )
    parser.add_argument(
        "--provenance-path",
        type=Path,
        default=ROOT / "docs" / "data_provenance.md",
        help="Markdown file updated with download provenance.",
    )
    return parser.parse_args()


def format_provenance(metadata_records: list[dict[str, object]]) -> str:
    lines = [
        "# Data Provenance",
        "",
        "This file is generated by `scripts/01_prepare_data.py` for Phase 1 step 1.",
        "It records raw GEO series-matrix downloads only.",
        "",
    ]
    for record in metadata_records:
        accession = str(record["accession"])
        lines.extend(
            [
                f"## {accession}",
                "",
                "- Retrieval method: `GEOparse.utils.download_from_url`",
                f"- Download date (UTC): `{record['downloaded_at_utc']}`",
                "- Raw files:",
            ]
        )
        for file_info in record["files"]:
            path_text = str(file_info["path"])
            checksum = str(file_info["sha256"])
            lines.append(f"  - `{path_text}`")
            lines.append(f"  - SHA-256: `{checksum}`")
        lines.append("")

    lines.extend(
        [
            "## Scope Notes",
            "",
            "- No labels parsed.",
            "- No processed matrices created.",
            "- No probe-to-symbol mapping performed.",
            "- No gene-space intersection performed.",
            "- External cohort downloaded and cache-prepared only.",
        ]
    )
    return "\n".join(lines) + "\n"


def relativize_metadata(
    metadata_records: list[dict[str, object]], root: Path
) -> list[dict[str, object]]:
    relativized = []
    for record in metadata_records:
        files = []
        for file_info in record["files"]:
            path_obj = Path(str(file_info["path"]))
            try:
                path_text = path_obj.relative_to(root).as_posix()
            except ValueError:
                path_text = path_obj.as_posix()
            files.append({"path": path_text, "sha256": file_info["sha256"]})
        relativized.append(
            {
                "accession": record["accession"],
                "downloaded_at_utc": record["downloaded_at_utc"],
                "files": files,
            }
        )
    return relativized


def main() -> None:
    args = parse_args()
    raw_dir = ensure_dir(args.raw_dir)
    ensure_dir(ROOT / "data" / "processed")

    metadata_records = []
    for accession in args.accessions:
        downloaded_paths = download_geo_series(accession=accession, raw_dir=raw_dir)
        metadata_records.append(
            collect_download_metadata(accession=accession, downloaded_paths=downloaded_paths)
        )

    provenance_text = format_provenance(relativize_metadata(metadata_records, ROOT))
    args.provenance_path.write_text(provenance_text, encoding="utf-8")


if __name__ == "__main__":
    main()
